#!/usr/bin/env sh
# https://typicode.github.io/husky/
. "$(dirname -- "$0")/_/husky.sh"

# Build the codebase to lib/ so that all configuration files are up-to-date.
npm run build
# Run the validation checks scoped to just the staged files prior to any changes being committed.
npx lint-staged --config ./lib/.lintstagedrc.mjs
